service: bikestore

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  include:
  - src/
  exclude:
  - node_modules/**/*

functions:
  bikes:
    handler: src/bikesHandler.listAll
    events:
    - http:
        path: bikes
        method: get
  getBike:
    handler: src/bikesHandler.get
    events:
    - http:
        path: bikes/{uuid}
        method: get
  newBike:
    handler: src/bikesHandler.newBike
    events:
    - http:
        path: bikes
        method: post
