import {
    autoGeneratedHashKey,
    rangeKey,
    table,
    attribute
  } from '@aws/dynamodb-data-mapper-annotations'

@table('bikes')
export class Bike {

  @autoGeneratedHashKey()
  uuid: string = ''

  @attribute()
  model: string = ''

  // constructor (uuid: string, model: string) {
  //   this.uuid = uuid
  //   this.model = model
  // }
}

export class BikeData {
  constructor (public model: string) {}
}
